w ="TusharGupta"
print(w.lower())
print(w.upper())
print(w.title())
print(w.capitalize())
print(w.find('Z'))
print(w.index('a',5))
print(w.isalpha())
print(w.isdigit())
print(w.isalnum())
y = chr(65)
print(type(y),y)
y =ord('H')
print(type(y),y)
x = "welcome to {} {}".format("Tushar","Gupta")
print(x)